In [ ]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series

# Pandas kutubxonasi bilan tanishamiz

In [ ]:
obj1 = Series([2,4,1,6,1.2,3.6]) # Serias malumot tuzulmasi

In [ ]:
print(obj1)

0    2.0
1    4.0
2    1.0
3    6.0
4    1.2
5    3.6
dtype: float64

In [ ]:
type(obj1)

pandas.core.series.Series

In [ ]:
obj1.values # Series dagi qiymatlarini ko'rish

array([2. , 4. , 1. , 6. , 1.2, 3.6])

In [ ]:
obj1.index # bu esa index ko'rish uchun

RangeIndex(start=0, stop=6, step=1)

In [ ]:
obj1[0]

2.0

In [ ]:

obj2 =Series([2,4,7,9],index=['a','b','c','d'])

In [ ]:
obj2

a    2
b    4
c    7
d    9
dtype: int64

In [ ]:
obj2['a']

2

In [ ]:
obj2[['a','b','c']]

a    2
b    4
c    7
dtype: int64

In [ ]:
obj2[obj2==2]

a    2
dtype: int64

In [ ]:
obj2

a    2
b    4
c    7
d    9
dtype: int64

In [ ]:
obj2*2

a     4
b     8
c    14
d    18
dtype: int64

# Lug'atdan series yaratish

In [ ]:
cars_firs = {'madel':'Lasetti','rangi':'oq', 'yili':2020, 'narxi':10000}

In [ ]:
type(cars_firs)

dict

In [ ]:
import pandas as pd
from pandas import Series

In [ ]:
obj = Series(cars_firs)

In [ ]:
obj

madel    Lasetti
rangi         oq
yili        2020
narxi      10000
dtype: object

In [ ]:
obj = Series({'madel':'Lasetti','rangi':'oq', 'yili':2020, 'narxi':10000})

In [ ]:
'madel' in obj

True

In [ ]:
cars2 = {'lasetti':1000,'tayota':20000,'malubu':30000,'bmv':50000}

In [ ]:
obj2 = Series(cars2)

In [ ]:
obj2

lasetti     1000
tayota     20000
malubu     30000
bmv        50000
dtype: int64

In [ ]:
cars = ['tayota','lasetti','malubu','hyunda','bmv']

In [ ]:
obj2 = Series(cars2, index=cars)

In [ ]:
obj2

tayota     20000.0
lasetti     1000.0
malubu     30000.0
hyunda         NaN
bmv        50000.0
dtype: float64

#Seriesda metodlari

In [ ]:
cars2

{'bmv': 50000, 'lasetti': 1000, 'malubu': 30000, 'tayota': 20000}

In [ ]:
obj2

tayota     20000.0
lasetti     1000.0
malubu     30000.0
hyunda         NaN
bmv        50000.0
dtype: float64

In [ ]:
obj2.isnull() # agar qiymat bo'lsa False qiymat qaytaradi

tayota     False
lasetti    False
malubu     False
hyunda      True
bmv        False
dtype: bool

In [ ]:
obj2.notnull() # notnull() bunda agar qiymat bo'lsa True qiymat qaytaradi

tayota      True
lasetti     True
malubu      True
hyunda     False
bmv         True
dtype: bool

In [ ]:
obj2

tayota     20000.0
lasetti     1000.0
malubu     30000.0
hyunda         NaN
bmv        50000.0
dtype: float64

In [ ]:
obj1 = Series({'tayota':20000,'bmv':3000,'lasetti':3500,'malubu':10000})

In [ ]:
obj1

tayota     20000
bmv         3000
lasetti     3500
malubu     10000
dtype: int64

In [ ]:
obj2+obj1

bmv        53000.0
hyunda         NaN
lasetti     4500.0
malubu     40000.0
tayota     40000.0
dtype: float64

#DataFrame ma'lumotlar tuzilmasi

In [ ]:
# DataFrame Series dan farqi ravishda 2 o'lchamli jadval ko'rinishida bo'ladi

In [ ]:
import pandas as pd

In [ ]:
 data = {
     'yil': [2021,2020,2019,2011],
     'Aholi': [139,333 , 44,11],
     'Temp': [1.58,1.48,1.22,1.55],
     'sonlar':[11,23,45,66]
}
df =pd.DataFrame(data)

In [ ]:
df

    yil  Aholi  Temp  sonlar
0  2021    139  1.58      11
1  2020    333  1.48      23
2  2019     44  1.22      45
3  2011     11  1.55      66

In [ ]:
df.sonlar

0    11
1    23
2    45
3    66
Name: sonlar, dtype: int64

In [ ]:
df.head(1)

    yil  Aholi  Temp
0  2021    139  1.58

In [ ]:
df.shape

(4, 4)

In [ ]:
df = pd.DataFrame(data, columns=['sonlar','yil','Temp','Aholi'])

In [ ]:
df

   sonlar   yil  Temp  Aholi
0      11  2021  1.58    139
1      23  2020  1.48    333
2      45  2019  1.22     44
3      66  2011  1.55     11

In [ ]:
df.sonlar

0    11
1    23
2    45
3    66
Name: sonlar, dtype: int64

In [ ]:
df

   sonlar   yil  Temp  Aholi
0      11  2021  1.58    139
1      23  2020  1.48    333
2      45  2019  1.22     44
3      66  2011  1.55     11

In [ ]:
df['yil']

0    2021
1    2020
2    2019
3    2011
Name: yil, dtype: int64

In [ ]:
df = pd.DataFrame(data, columns=['yil','Temp','Aholi','yangi'])

In [ ]:
df

    yil  Temp  Aholi yangi
0  2021  1.58    139   NaN
1  2020  1.48    333   NaN
2  2019  1.22     44   NaN
3  2011  1.55     11   NaN

In [ ]:
df['yangi'] = [1.11,1.23,2.44,2.45]

In [ ]:
df.head()

    yil  Temp  Aholi  yangi
0  2021  1.58    139   1.11
1  2020  1.48    333   1.23
2  2019  1.22     44   2.44
3  2011  1.55     11   2.45

In [ ]:
df['1500+']= df.Aholi>100

In [ ]:
df.head()

   sonlar   yil  Temp  Aholi  1500+
0      11  2021  1.11    139   True
1      23  2020  1.23    333   True
2      45  2019  2.44     44  False
3      66  2011  2.45     11  False

In [ ]:
var = pd.Series([12,13,15,16])

In [ ]:
df.yangi = var

In [ ]:
df.head()

    yil  Temp  Aholi  yangi  1500+
0  2021  1.58    139     12   True
1  2020  1.48    333     13   True
2  2019  1.22     44     15  False
3  2011  1.55     11     16  False

In [ ]:
df

    yil  Temp  Aholi  yangi  1500+
0  2021  1.58    139     12   True
1  2020  1.48    333     13   True
2  2019  1.22     44     15  False
3  2011  1.55     11     16  False

#Lug'atdan DataFrame yaratish

In [ ]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9,2011:17.6},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2011:17.8}
}

In [ ]:
df = pd.DataFrame(data)
df

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2011        17.6        17.8

In [ ]:
df.index.name = 'name' # indexga nom berish

In [ ]:
df.head()

      Uzbekistan  Kazakhstan
name
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1

In [ ]:
df3 = pd.DataFrame(data, index=[2021,2020])

In [ ]:
df3.head()

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7

In [ ]:
df3.T  # Ustunlarini o'zgartirish

            2021  2020
Uzbekistan  33.9  33.5
Kazakhstan  18.9  18.7

In [ ]:
obj = df3.values

In [ ]:
type(obj)

numpy.ndarray

In [ ]:
obj

array([[33.9, 18.9],
       [32.9, 18.5],
       [33.5, 18.7]])

In [ ]:
df3

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7

In [ ]:
Index =df2.index

In [ ]:
Index[0]

2021

In [ ]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445",'azamat':'azamat1796','azamat':'azikjon1796'}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com",'azamat':'azamatsabina1796@mail.ru','azamat':'azamat@mail.ru'}

data = {
    'username':usernames,
    'email':emails
}
df = pd.DataFrame(data)

In [ ]:
data2 = {
    'username':{"olim":"olimjon21", "maryam":"maryam2020"},
    'email':{"olim":"olimjon21@mail.ru", "maryam":"maryam20@gmail.com"}
}

In [ ]:
df2 = df.append(pd.DataFrame(data2))

In [ ]:
df2

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
azamat   azikjon1796        azamat@mail.ru
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [ ]:
df2['username']=='olimtoy'

anvar      False
olim        True
maryam     False
javohir    False
azamat     False
olim       False
maryam     False
Name: username, dtype: bool

# indexlash

In [ ]:
print(df2)

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
azamat   azikjon1796        azamat@mail.ru
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [ ]:
df2

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
azamat   azikjon1796        azamat@mail.ru
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [ ]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}

In [ ]:
df3 = pd.DataFrame(data, columns=['Uzbekistan','Kazakhstan'])

In [ ]:
df3.head()

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1

In [ ]:
indeks = df3.index

In [ ]:
indeks

Int64Index([2021, 2020, 2019, 2018, 2017, 2016], dtype='int64')

In [ ]:
df3.columns

Index(['Uzbekistan', 'Kazakhstan'], dtype='object')

#Index metodlari

In [ ]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com"}

data = {
    'username':usernames,
    'email':emails
}
df = pd.DataFrame(data)

In [ ]:
data2 = {
    'username':{"olim":"olimjon21", "maryam":"maryam2020"},
    'email':{"olim":"olimjon21@mail.ru", "maryam":"maryam20@gmail.com"}
}

In [ ]:
df1 = df.append(pd.DataFrame(data2))
df1

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
azamat   azikjon1796        azamat@mail.ru

In [ ]:
df

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
azamat   azikjon1796        azamat@mail.ru

In [ ]:
df1.index

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
indeks = df1.index

In [ ]:
indeks

Index(['anvar', 'olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
Index = pd.Index(['azamat','abdullo','hasan','olim'])

In [ ]:
Index

Index(['azamat', 'abdullo', 'hasan', 'olim'], dtype='object')

In [ ]:
type(Index)

pandas.core.indexes.base.Index

In [ ]:
df1

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

In [ ]:
df1.isin(Index) # bu shart Index degan obj ni df1 ichidagi index bormi 
Index.isin(df1.index)

array([False, False, False,  True])

In [ ]:
Index

Index(['azamat', 'abdullo', 'hasan', 'olim'], dtype='object')

In [ ]:
df1.index.difference(Index) # bu indexlar farqini chiqaradi 
Index.difference(df1.index)

Index(['abdullo', 'azamat', 'hasan'], dtype='object')

In [ ]:
df1.index.union(Index) # indexlashni jamlash

Index(['abdullo', 'anvar', 'azamat', 'hasan', 'javohir', 'maryam', 'maryam',
       'olim', 'olim'],
      dtype='object')

In [ ]:
df1.index.delete(0) # indexlarni o'chirish

Index(['olim', 'maryam', 'javohir', 'olim', 'maryam'], dtype='object')

In [ ]:
df1

            username                 email
anvar    anvarbek223       anvar@gmail.com
olim         olimtoy          olim@mail.ru
maryam    mary334455      mary33@gmail.com
javohir   javohir445  javohir445@gmail.com
olim       olimjon21     olimjon21@mail.ru
maryam    maryam2020    maryam20@gmail.com

#Qayta indexlash

In [ ]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}
df = pd.DataFrame(data)

In [ ]:
df

      Uzbekistan  Kazakhstan
2021        33.9        18.9
2020        33.5        18.7
2019        32.9        18.5
2018        32.5        18.3
2017        31.9        18.1
2016         NaN        17.8

In [ ]:
df.index = [21,20,19,18,17,16]
df.index.name = 'index'

In [ ]:
df

       Uzbekistan  Kazakhstan
index
21           33.9        18.9
20           33.5        18.7
19           32.9        18.5
18           32.5        18.3
17           31.9        18.1
16            NaN        17.8

In [ ]:
# agar biz indexlarmi tartiblamoqchi bo'lsak Reindex foydalanadi

In [ ]:
index = [21,20,19,18,17,16]

In [ ]:
index.sort()

In [ ]:
df = df.reindex(index)

In [ ]:
df

       Uzbekistan  Kazakhstan
index
16            NaN        17.8
17           31.9        18.1
18           32.5        18.3
19           32.9        18.5
20           33.5        18.7
21           33.9        18.9

In [ ]:
 df.reindex(index=range(15,22), method = 'nearest')
#  df.reindex(index = range(15,22), method='ffill')

       Uzbekistan  Kazakhstan
index
15            NaN        17.8
16            NaN        17.8
17           31.9        18.1
18           32.5        18.3
19           32.9        18.5
20           33.5        18.7
21           33.9        18.9

In [ ]:
df

       Uzbekistan  Kazakhstan
index
16            NaN        17.8
17           31.9        18.1
18           32.5        18.3
19           32.9        18.5
20           33.5        18.7
21           33.9        18.9

In [ ]:
df2 = df.reindex(columns=['Uzbekistan'])
df2

       Uzbekistan
index
16            NaN
17           31.9
18           32.5
19           32.9
20           33.5
21           33.9

In [ ]:
df[['Uzbekistan']]

       Uzbekistan
index
16            NaN
17           31.9
18           32.5
19           32.9
20           33.5
21           33.9

In [ ]:
df2.head()

       Uzbekistan
index
16            NaN
17           31.9
18           32.5
19           32.9
20           33.5

In [ ]:
df2.sample(3)

       Uzbekistan
index
18           32.5
17           31.9
16            NaN

In [ ]:
obj= df2.loc[17:18, 'Uzbekistan']

# Elementlarni tashlab yuborish

In [ ]:
df

    Uzbekistan  Kazakhstan
16         NaN        17.8
17        31.9        18.1
18        32.5        18.3
19        32.9        18.5
20        33.5        18.7
21        33.9        18.9

In [ ]:
df2 = df.drop(20)

In [ ]:
df2

    Uzbekistan  Kazakhstan
16         NaN        17.8
17        31.9        18.1
18        32.5        18.3
19        32.9        18.5
21        33.9        18.9

In [ ]:
df2 = df.drop([20,21,19])

In [ ]:
df2

    Uzbekistan  Kazakhstan
16         NaN        17.8
17        31.9        18.1
18        32.5        18.3

In [ ]:
df2 = df.drop('Uzbekistan',axis=1)
# df.drop('Uzbekistan',axis=1,inplace=True) # bu haqiqiy datamizda ham o'zgaradi

In [ ]:
df2

    Kazakhstan
16        17.8
17        18.1
18        18.3
19        18.5
20        18.7
21        18.9

# indexlash qator va ustunnitanlash va filterlash

In [ ]:
data = {'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
       'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
       'Temp':[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
       'Zichlik':[79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]}

In [ ]:
df = pd.DataFrame(data)
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [ ]:
data = df['Yil']

In [ ]:
type(data)

pandas.core.series.Series

In [ ]:
data

0    2021
1    2020
2    2019
3    2018
4    2017
5    2016
6    2015
7    2010
Name: Yil, dtype: int64

In [ ]:
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [ ]:
data = df[['Aholi soni','Yil']]
data

   Aholi soni   Yil
0        33.9  2021
1        33.5  2020
2        32.9  2019
3        32.5  2018
4        31.9  2017
5        31.4  2016
6        30.9  2015
7        28.5  2010

In [ ]:
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [ ]:
index =[21,20,19,18,17,16,15,10]

In [ ]:
index.sort()

    Yil  Aholi soni  Temp  Zichlik
10  NaN         NaN   NaN      NaN
15  NaN         NaN   NaN      NaN
16  NaN         NaN   NaN      NaN
17  NaN         NaN   NaN      NaN
18  NaN         NaN   NaN      NaN
19  NaN         NaN   NaN      NaN
20  NaN         NaN   NaN      NaN
21  NaN         NaN   NaN      NaN

In [ ]:
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [ ]:
print(df)

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [ ]:
df

    Yil  Aholi soni  Temp  Zichlik
0  2021        33.9  1.54    79.77
1  2020        33.5  1.48    78.68
2  2019        32.9  1.56    77.53
3  2018        32.5  1.62    76.34
4  2017        31.9  1.65    75.13
5  2016        31.4  1.66    73.91
6  2015        30.9  1.64    72.71
7  2010        28.5  1.53    67.03

In [ ]:
 obj  =df['Aholi soni']

In [ ]:
type(obj)

pandas.core.series.Series

In [ ]:
obj = df[['Aholi soni']]
type(obj)

pandas.core.frame.DataFrame

In [ ]:
obj

0    33.9
1    33.5
2    32.9
3    32.5
4    31.9
5    31.4
6    30.9
7    28.5
Name: Aholi soni, dtype: float64

In [ ]:
data[1
     ]

2020

In [ ]:
type(data)

pandas.core.series.Series

In [ ]:
data

0    2021
1    2020
2    2019
3    2018
4    2017
5    2016
6    2015
7    2010
Name: Yil, dtype: int64

In [ ]:
obj =data.reindex(index=['a','b','c','d','f','g','h','r'])

In [ ]:
obj

a   NaN
b   NaN
c   NaN
d   NaN
f   NaN
g   NaN
h   NaN
r   NaN
Name: Yil, dtype: float64

In [ ]:
obj = pd.Series(np.arange(5), index= ['a','b','c','d','f'])

In [ ]:
obj

a    0
b    1
c    2
d    3
f    4
dtype: int64

In [ ]:
obj['a']

0

# Dataframe ustida amallar

In [ ]:
uz = {2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9, 2016:31.4, 2015:30.9}
kz = {2020:18.8, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8, 2015:17.6}
tj = {2020:9.5, 2019:9.3, 2018:9.1, 2017:8.9, 2016:8.7, 2015:8.5}
kg = {2020:6.5, 2019:6.4, 2018:6.3, 2017:6.2, 2016:6.1, 2015:6.0}
tr = {2020:6.0, 2019:5.9, 2018:5.9, 2017:5.8, 2016:5.6, 2015:5.6}

df = pd.DataFrame(
    {'Uzbekistan':uz,
     'Kazakhstan':kz,
     'Tajikistan':tj,
     'Kyrgizstan':kg,
     'Turkmenistan':tr
    }
)

In [ ]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
df['Uzbekistan']

2020    33.5
2019    32.9
2018    32.5
2017    31.9
2016    31.4
2015    30.9
Name: Uzbekistan, dtype: float64

In [ ]:
df['Uzbekistan'].to_numpy()

array([33.5, 32.9, 32.5, 31.9, 31.4, 30.9])

In [ ]:
df[['Uzbekistan']].to_numpy()

array([[33.5],
       [32.9],
       [32.5],
       [31.9],
       [31.4],
       [30.9]])

In [ ]:
df[['Uzbekistan','Tajikistan']]

      Uzbekistan  Tajikistan
2020        33.5         9.5
2019        32.9         9.3
2018        32.5         9.1
2017        31.9         8.9
2016        31.4         8.7
2015        30.9         8.5

In [ ]:
df[4:]

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
df>10

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        True        True       False       False         False
2019        True        True       False       False         False
2018        True        True       False       False         False
2017        True        True       False       False         False
2016        True        True       False       False         False
2015        True        True       False       False         False

In [ ]:
df>5

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        True        True        True        True          True
2019        True        True        True        True          True
2018        True        True        True        True          True
2017        True        True        True        True          True
2016        True        True        True        True          True
2015        True        True        True        True          True

In [ ]:
df[['Uzbekistan']][df['Uzbekistan']>30]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5
2017        31.9
2016        31.4
2015        30.9

In [ ]:
dfuz = df[['Uzbekistan']]

In [ ]:
dfuz[dfuz>30]

      Uzbekistan
2020        33.5
2019        32.9
2018        32.5
2017        31.9
2016        31.4
2015        30.9

In [ ]:
df2 = df.transpose(copy=True)

In [ ]:
df2

              2020  2019  2018  2017  2016  2015
Uzbekistan    33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan    18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan     9.5   9.3   9.1   8.9   8.7   8.5
Kyrgizstan     6.5   6.4   6.3   6.2   6.1   6.0
Turkmenistan   6.0   5.9   5.9   5.8   5.6   5.6

In [ ]:
df2[df2[2015]>6]

            2020  2019  2018  2017  2016  2015
Uzbekistan  33.5  32.9  32.5  31.9  31.4  30.9
Kazakhstan  18.8  18.5  18.3  18.1  17.8  17.6
Tajikistan   9.5   9.3   9.1   8.9   8.7   8.5

# loc iloc haqida

In [ ]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
df.loc[[2018]] # loc bu ustunlarni chiqarish uchun ishlatiladi

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2018        32.5        18.3         9.1         6.3           5.9

In [ ]:
df.loc[[2020]]>30

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        True       False       False       False         False

In [ ]:
df.loc[[2020,2019],['Uzbekistan']] # bunda ham ustun ham qator bo'yicha filterlash

      Uzbekistan
2020        33.5
2019        32.9

In [ ]:
df.iloc[[1,2]] # iloc funksiyasi bizga index raqami bo'yicha chiqarishga yordam beradi

       Uzbekistan  Kazakhstan
index
17           31.9        18.1
18           32.5        18.3

In [ ]:
df.iloc[[1,2],[0,2]] # ustunlarni tartib raqami bo'yicha

      Uzbekistan  Tajikistan
2019        32.9         9.3
2018        32.5         9.1

In [ ]:
# agar bi bitta qiymatni chiqarmoqchi bo'lsak at metodidan foydalanamiz 
df.at[2015, 'Uzbekistan']

30.9

In [ ]:
df.at[2015, 'Uzbekistan']- df.at[2015,'Tajikistan']

22.4

In [ ]:
#endi biz bu elemtlarni tartib raqami bilan yozsak iat methodidan foyladamiz 
df.iat[1,1]
# df

18.5

In [ ]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
obj = pd.Series(
    [
        "Andijon",
        "Buxoro",
        "Farg'ona",
        "Jizzax",
        "Xorazm",
        "Namangan",
        "Navoiy",
        "Qashqadaryo",
        "Qoraqalpog'iston Respublikasi",
        "Samarqand",
        "Sirdaryo",
        "Surxondaryo",
        "Toshkent",
    ]
)
print(obj)

0                           Andijon
1                            Buxoro
2                          Farg'ona
3                            Jizzax
4                            Xorazm
5                          Namangan
6                            Navoiy
7                       Qashqadaryo
8     Qoraqalpog'iston Respublikasi
9                         Samarqand
10                         Sirdaryo
11                      Surxondaryo
12                         Toshkent
dtype: object

In [ ]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

In [ ]:
df

      Uzbekistan  Kazakhstan  Tajikistan  Kyrgizstan  Turkmenistan
2020        33.5        18.8         9.5         6.5           6.0
2019        32.9        18.5         9.3         6.4           5.9
2018        32.5        18.3         9.1         6.3           5.9
2017        31.9        18.1         8.9         6.2           5.8
2016        31.4        17.8         8.7         6.1           5.6
2015        30.9        17.6         8.5         6.0           5.6

# dataframe va Series o'rtasida amallar

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [ ]:
print(s1)
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape(3,3), columns=list('bcd'), index=['Olma','Anor','Uzum'])
df2 = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('abc'), index=['Olma','Anor','Qovun','Anjir'])

In [ ]:
df1

        b    c    d
Olma  0.0  1.0  2.0
Anor  3.0  4.0  5.0
Uzum  6.0  7.0  8.0

In [ ]:
df2

         a     b     c
Olma   0.0   1.0   2.0
Anor   3.0   4.0   5.0
Qovun  6.0   7.0   8.0
Anjir  9.0  10.0  11.0

In [ ]:
df1+df2

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  7.0  9.0 NaN
Olma  NaN  1.0  3.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [ ]:
df1.add(df2, fill_value=0) # Qo'shish methodi

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   7.0   9.0  5.0
Olma   0.0   1.0   3.0  2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN   6.0   7.0  8.0

In [ ]:
df2.sub(df1,fill_value=0) # ayirish methodi

         a     b     c    d
Anjir  9.0  10.0  11.0  NaN
Anor   3.0   1.0   1.0 -5.0
Olma   0.0   1.0   1.0 -2.0
Qovun  6.0   7.0   8.0  NaN
Uzum   NaN  -6.0  -7.0 -8.0

In [ ]:
df2.sub(df1)

        a    b    c   d
Anjir NaN  NaN  NaN NaN
Anor  NaN  1.0  1.0 NaN
Olma  NaN  1.0  1.0 NaN
Qovun NaN  NaN  NaN NaN
Uzum  NaN  NaN  NaN NaN

In [ ]:
df2.div(df1, fill_value=1)

         a          b          c      d
Anjir  9.0  10.000000  11.000000    NaN
Anor   3.0   1.333333   1.250000  0.200
Olma   0.0        inf   2.000000  0.500
Qovun  6.0   7.000000   8.000000    NaN
Uzum   NaN   0.166667   0.142857  0.125

In [ ]:
df = pd.DataFrame(np.arange(1,13.).reshape(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

   Olma  Anor  Qovun  Anjir
a   1.0   2.0    3.0    4.0
b   5.0   6.0    7.0    8.0
c   9.0  10.0   11.0   12.0

In [ ]:
obj = pd.Series([1,1,2,2], index=df.columns)
obj

Olma     1
Anor     1
Qovun    2
Anjir    2
dtype: int64

In [ ]:
df.add(obj)

   Olma  Anor  Qovun  Anjir
a   2.0   3.0    5.0    6.0
b   6.0   7.0    9.0   10.0
c  10.0  11.0   13.0   14.0

In [ ]:
import requests
mohirdev = "https://jovian.ai/anvarnarz/03-pandas-04-dars/v/1?utm_source=embed"
responce = requests.get(mohirdev)
print(responce)

<Response [200]>

In [ ]:
#pandas Obyekti elementlariga Funksiyalarni qo'llash

In [ ]:
df = pd.DataFrame(np.random.randn(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

       Olma      Anor     Qovun     Anjir
a  1.362692  0.158830  0.381182  0.375363
b  0.610263 -1.201842  0.206837 -0.001334
c -0.485252 -1.152455  0.916123  0.019778

In [ ]:
# df.abs()
np.abs(df) # funksiya qo'shish

       Olma      Anor     Qovun     Anjir
a  1.362692  0.158830  0.381182  0.375363
b  0.610263  1.201842  0.206837  0.001334
c  0.485252  1.152455  0.916123  0.019778

In [ ]:
np.round(df) # bu sonlarni yaxlitlab beradi

   Olma  Anor  Qovun  Anjir
a   1.0   0.0    0.0    0.0
b   1.0  -1.0    0.0   -0.0
c  -0.0  -1.0    1.0    0.0

In [ ]:
df

       Olma      Anor     Qovun     Anjir
a  1.362692  0.158830  0.381182  0.375363
b  0.610263 -1.201842  0.206837 -0.001334
c -0.485252 -1.152455  0.916123  0.019778

In [ ]:
df.mean() # bu olma ustun uchun o'rtacha qiymat

Olma     0.495901
Anor    -0.731822
Qovun    0.501381
Anjir    0.131269
dtype: float64

In [ ]:
df.mean(axis=1)

a    0.569517
b   -0.096519
c   -0.175451
dtype: float64

In [ ]:
df.apply(sum, axis=1) # summani hisoblash

a    2.278068
b   -0.386076
c   -0.701806
dtype: float64

In [ ]:
df.sum()

Olma     1.487703
Anor    -2.195467
Qovun    1.504143
Anjir    0.393807
dtype: float64

In [ ]:
f = lambda x : x.max()- x.min()

In [ ]:
df.apply(f)

Olma     1.847944
Anor     1.360673
Qovun    0.709286
Anjir    0.376697
dtype: float64

In [ ]:
def foo(x):
  return pd.Series([x.max(), x.min()], index=['max','min'])

In [ ]:
df.apply(foo)

         Olma      Anor     Qovun     Anjir
max  1.362692  0.158830  0.916123  0.375363
min -0.485252 -1.201842  0.206837 -0.001334

In [ ]:
df.applymap(abs) # bu funksiya har bir elementi uchun alohida funksiyani qo'llab chiqadi

       Olma      Anor     Qovun     Anjir
a  1.362692  0.158830  0.381182  0.375363
b  0.610263  1.201842  0.206837  0.001334
c  0.485252  1.152455  0.916123  0.019778

In [ ]:
df = pd.DataFrame(np.arange(1,13).reshape(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
df

   Olma  Anor  Qovun  Anjir
a     1     2      3      4
b     5     6      7      8
c     9    10     11     12

In [ ]:
df.apply(lambda x:x*x)

   Olma  Anor  Qovun  Anjir
a     1     4      9     16
b    25    36     49     64
c    81   100    121    144

# Tartiblash(sort) Reytinglash (ranking)

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [ ]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s2.sort_index()

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
obj = pd.Series(range(5), index= ['d','c','b','a','f'])

In [ ]:
obj

d    0
c    1
b    2
a    3
f    4
dtype: int64

In [ ]:
obj.sort_index()

a    3
b    2
c    1
d    0
f    4
dtype: int64

In [ ]:
obj.sort_values()

d    0
c    1
b    2
a    3
f    4
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
# KEling keyingi mashqlar uchun Githubdan kattaroq DF yuklab olamiz
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv', index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [ ]:
df.shape

(2499, 12)

In [ ]:
df.sort_index(axis=1) # bu bizda ustunlari bo'yicha tartiblash

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [ ]:
df.sort_index(axis=1,inplace=True)

In [ ]:
df.head()

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018

In [ ]:
df.sort_index(ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008

In [ ]:
df.sort_values(by=['price'],ascending=False) # bu price bo'yicha sortlash

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
502,84900,mercedes-benz,sl-class,2017,clean vehicle,25302,silver,wddjk7ea3hf044968,167607883,florida,usa,2 days left
1340,74000,ford,drw,2019,clean vehicle,10536,no_color,1ft8w4dt6ked32656,167780682,illinois,usa,2 days left
1336,70000,ford,drw,2019,clean vehicle,9643,no_color,1ft8w3dt3kee48276,167780680,illinois,usa,2 days left
277,67000,dodge,challenger,2019,clean vehicle,10944,blue,2c3cdzl97kh518237,167759490,ohio,usa,21 hours left
1215,65500,ford,srw,2019,clean vehicle,6500,black,1ft7w2bt0kec44818,167718954,indiana,usa,21 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
141,0,dodge,van,2008,salvage insurance,177948,orange,2d8hn44h88r669549,167756157,utah,usa,2 days left
391,0,cadillac,coupe,2000,salvage insurance,105169,white,1g6el12y9yu148063,167651218,virginia,usa,9 days left
285,0,ford,door,2000,salvage insurance,124969,black,1fafp34p7yw270338,167251902,oklahoma,usa,17 hours left
290,0,mazda,door,2009,salvage insurance,117541,gray,jm3er293590215768,167543177,indiana,usa,16 hours left
354,0,ford,pickup,2009,salvage insurance,180364,blue,1ftyr10d19pa60391,167360535,tennessee,usa,2 days left

In [ ]:
df.sort_index(axis=1)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [ ]:
df = df.sort_values(by=['price','brand'], ascending=False)

In [ ]:
df.head()

                   maydoni    aholisi
Boʻlinishi
Andijon viloyati    4200.0  1899000.0
Buxoro viloyati    39400.0  1384700.0
Fargʻona viloyati   6800.0  2597000.0
Jizzax viloyati    20500.0   910500.0
Xorazm viloyati     6300.0  1200000.0

In [ ]:
df['reting'] = df['year'].rank()

In [ ]:
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,reting
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,70.5
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,115.0
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,1362.0
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,336.5
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,1362.0

In [ ]:
df.sort_values('year')

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,reting
32,29800,chevrolet,camaro,1973,clean vehicle,46226,red,1q87t3n166389,167763370,pennsylvania,usa,22 hours left,1.0
405,25,ford,door,1984,salvage insurance,41577,white,2ftcf15y9eca14589,167611661,arkansas,usa,17 hours left,2.0
545,0,gmc,door,1993,salvage insurance,0,light blue,1gkfk16k5pj701631,167358601,colorado,usa,18 hours left,3.0
362,25,ford,pickup,1994,salvage insurance,206162,white,1ftdf15y2rnb12612,167361489,georgia,usa,2 days left,4.5
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,55600,lexus,gx,2020,clean vehicle,8186,silver,jtjam7bx4l5251250,167605747,florida,usa,2 days left,2475.5
806,28300,chevrolet,colorado,2020,clean vehicle,13886,silver,1gcgtcen7l1101496,167805497,indiana,usa,2 days left,2475.5
2322,15000,nissan,altima,2020,clean vehicle,14320,blue,1n4bl4cv4lc134145,167656212,ohio,usa,2 days left,2475.5
2344,20100,nissan,rogue,2020,clean vehicle,10875,blue,jn8at2mvxlw103235,167614842,minnesota,usa,14 hours left,2475.5
1388,17000,ford,fusion,2020,clean vehicle,1117,gray,3fa6p0d98lr194138,167742945,pennsylvania,usa,2 days left,2475.5

In [ ]:
df['reting'] = df['price'].rank(method='min')

In [ ]:
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,reting
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,380.0
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,156.0
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,326.0
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,1824.0
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,2004.0

In [ ]:
df['reting'] = df['mileage'].rank(method='average') # moshina yurgan km o'rtacha qiymat bo'yicha retinglash

In [ ]:
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,reting
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left,2486.0
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left,2445.0
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left,1430.0
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left,1881.0
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left,77.0

# dataset statistika bilan ishlash

In [ ]:
# Keyingi mashqlar uchun ma'lumotlarni Githubdan yuklab olamiz
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/uzbekistan.csv', index_col=0)
df.columns = ['maydoni','aholisi']
df.head()

                   maydoni    aholisi
Boʻlinishi
Andijon viloyati    4200.0  1899000.0
Buxoro viloyati    39400.0  1384700.0
Fargʻona viloyati   6800.0  2597000.0
Jizzax viloyati    20500.0   910500.0
Xorazm viloyati     6300.0  1200000.0

In [ ]:
df.sum()

maydoni      441900.0
aholisi    22945800.0
dtype: float64

In [ ]:
df2 = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/gm_sales.csv", index_col=0)
df2.head()

         2020   2021
Labo     4521   7542
Damas   30889  33682
Spark   16370   6485
Nexia   41663  14442
Cobalt  44901  36317

In [ ]:
df2.sum(axis=1)

Labo      12063
Damas     64571
Spark     22855
Nexia     56105
Cobalt    81218
Gentra    56634
dtype: int64

In [ ]:
df2.mean(axis=1)

Labo       6031.5
Damas     32285.5
Spark     11427.5
Nexia     28052.5
Cobalt    40609.0
Gentra    28317.0
dtype: float64

##Boshqa funksiyalar

`count` - NaN bo'lmagan qiymatlar soni

`median` - qiymatlar medianini hisbolash

`mad` - mean absolute deviation 

`prod` - barcha qiymatlar ko'paytmasi

`var` - variance (dispersiya)

`std` - standart deviation (standart chetlanis)

`skew` - skewness

`kurt` - kurtosis

`cumsum` - cumulative sum

`cummin` va `cummax`- cumulative min and max

`cumprod` - cumulative product

`diff` - arifmetik farq (difference)

`pct_change` - percent changes

In [ ]:
df.idxmin()  # eng kichik qiymatnilarni topib beradi

maydoni     Andijon viloyati
aholisi    Sirdaryo viloyati
dtype: object

In [ ]:
df['aholisi'].argmin() # bu funksiya eng kichik qiymat indexni qaytaradi

10

In [ ]:
df.iloc[10]

maydoni      5100.0
aholisi    648100.0
Name: Sirdaryo viloyati, dtype: float64

In [ ]:
df.sample(5)

                      maydoni    aholisi
Boʻlinishi
Toshkent viloyati     15300.0  4450000.0
Andijon viloyati       4200.0  1899000.0
Surxondaryo viloyati  20800.0  1676000.0
Namangan viloyati      7900.0  1862000.0
Xorazm viloyati        6300.0  1200000.0

In [ ]:
df.tail()

                                maydoni    aholisi
Boʻlinishi
Qoraqalpogʻiston Respublikasi  160000.0  1200000.0
Samarqand viloyati              16400.0  2322000.0
Sirdaryo viloyati                5100.0   648100.0
Surxondaryo viloyati            20800.0  1676000.0
Toshkent viloyati               15300.0  4450000.0

In [ ]:
df.keys()

Index(['maydoni', 'aholisi'], dtype='object')

In [ ]:
df.aholisi

Boʻlinishi
Andijon viloyati                 1899000.0
Buxoro viloyati                  1384700.0
Fargʻona viloyati                2597000.0
Jizzax viloyati                   910500.0
Xorazm viloyati                  1200000.0
Namangan viloyati                1862000.0
Navoiy viloyati                   767500.0
Qashqadaryo viloyati             2029000.0
Qoraqalpogʻiston Respublikasi    1200000.0
Samarqand viloyati               2322000.0
Sirdaryo viloyati                 648100.0
Surxondaryo viloyati             1676000.0
Toshkent viloyati                4450000.0
Name: aholisi, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, Andijon viloyati to Toshkent viloyati
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   maydoni  13 non-null     float64
 1   aholisi  13 non-null     float64
dtypes: float64(2)
memory usage: 868.0+ bytes

In [ ]:
df.describe()

             maydoni       aholisi
count      13.000000  1.300000e+01
mean    33992.307692  1.765062e+06
std     47224.895651  1.003012e+06
min      4200.000000  6.481000e+05
25%      6800.000000  1.200000e+06
50%     16400.000000  1.676000e+06
75%     28400.000000  2.029000e+06
max    160000.000000  4.450000e+06

# dataset statistika correlyatsiya

In [ ]:
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [ ]:
df['price'].corr(df['year'])

0.4182735684917942

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv')
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [ ]:
df['year'].corr(df['price']) # bu corr() funksiya o'zaro solishtirishni amalga oshoradi

0.5207118525518949

0.5207118525518949

In [ ]:
df['year'].corr(df['mileage'])

-0.7380268515364232

In [ ]:
df.corr() # bu umumy hammasisini solishtirishni amalga oshiradi

                year     price   mileage       tax       mpg  engineSize
year        1.000000  0.520712 -0.738027  0.012480 -0.094626   -0.142147
price       0.520712  1.000000 -0.537214  0.268717 -0.438445    0.516126
mileage    -0.738027 -0.537214  1.000000 -0.160223  0.202850    0.063652
tax         0.012480  0.268717 -0.160223  1.000000 -0.513742    0.338341
mpg        -0.094626 -0.438445  0.202850 -0.513742  1.000000   -0.339862
engineSize -0.142147  0.516126  0.063652  0.338341 -0.339862    1.000000

In [ ]:

df.corrwith(df['price'])

year          0.520712
price         1.000000
mileage      -0.537214
tax           0.268717
mpg          -0.438445
engineSize    0.516126
dtype: float64

In [ ]:
madels = df['model'].unique()

In [ ]:
len(madels)

27

NameError: ignored

In [ ]:
df['model'].value_counts()

 C Class      3747
 A Class      2561
 E Class      1953
 GLC Class     960
 GLA Class     847
 B Class       591
 CL Class      511
 GLE Class     461
 SL CLASS      260
 CLS Class     237
 V Class       207
 S Class       197
 GL Class      121
 SLK            95
 CLA Class      86
 X-CLASS        82
 M Class        79
 GLS Class      74
 GLB Class      19
 G Class        15
 CLK             7
 CLC Class       3
 R Class         2
180              1
230              1
220              1
200              1
Name: model, dtype: int64

In [ ]:
df.head()

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
1,S Class,2017,34948,Automatic,27000,Hybrid,20,61.4,2.1
2,SL CLASS,2016,49948,Automatic,6200,Petrol,555,28.0,5.5
3,G Class,2016,61948,Automatic,16000,Petrol,325,30.4,4.0
4,G Class,2016,73948,Automatic,4000,Petrol,325,30.1,4.0

In [ ]:
df['fuelType'].value_counts()

Diesel    9187
Petrol    3752
Hybrid     173
Other        7
Name: fuelType, dtype: int64

In [ ]:
df['model'].unique()

array([' SLK', ' S Class', ' SL CLASS', ' G Class', ' GLE Class',
       ' GLA Class', ' A Class', ' B Class', ' GLC Class', ' C Class',
       ' E Class', ' GL Class', ' CLS Class', ' CLC Class', ' CLA Class',
       ' V Class', ' M Class', ' CL Class', ' GLS Class', ' GLB Class',
       ' X-CLASS', '180', ' CLK', ' R Class', '230', '220', '200'],
      dtype=object)

In [ ]:
models = [' SLK',' A Class']

In [ ]:
filtr = df['model'].isin(models)

In [ ]:
df[filtr]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,SLK,2005,5200,Automatic,63000,Petrol,325,32.1,1.8
10,A Class,2020,32980,Automatic,606,Petrol,145,35.8,2.0
11,A Class,2020,26980,Automatic,1000,Diesel,145,62.8,1.5
33,A Class,2020,28128,Automatic,2563,Petrol,145,47.9,1.3
34,A Class,2019,23184,Manual,1173,Petrol,145,44.8,1.3
...,...,...,...,...,...,...,...,...,...
13060,A Class,2017,109495,Automatic,1755,Petrol,145,24.8,4.0
13066,A Class,2019,23440,Automatic,10124,Petrol,145,53.3,1.3
13090,A Class,2015,12995,Automatic,34665,Diesel,20,70.6,1.5
13108,SLK,2016,17499,Automatic,30128,Diesel,30,70.6,2.1
13109,A Class,2017,16499,Automatic,20477,Diesel,145,68.9,2.1

In [ ]:
df[(df['year']>2019) & (df.price>20000)] # jadvallarni filterlash 2 va undan ortiq shartlarni berishimiz munkin

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
10,A Class,2020,32980,Automatic,606,Petrol,145,35.8,2.0
11,A Class,2020,26980,Automatic,1000,Diesel,145,62.8,1.5
33,A Class,2020,28128,Automatic,2563,Petrol,145,47.9,1.3
38,C Class,2020,31790,Automatic,3500,Petrol,145,64.2,2.0
57,GLE Class,2020,48995,Automatic,3000,Diesel,145,36.7,2.0
...,...,...,...,...,...,...,...,...,...
13053,A Class,2020,27995,Automatic,2500,Diesel,145,67.3,1.5
13056,GLE Class,2020,58450,Automatic,1159,Diesel,150,32.8,2.9
13113,C Class,2020,30999,Automatic,1000,Diesel,145,64.2,2.0
13114,C Class,2020,35999,Automatic,500,Diesel,145,55.4,2.0
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0

In [ ]:
df[df.year==2020]

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
10,A Class,2020,32980,Automatic,606,Petrol,145,35.8,2.0
11,A Class,2020,26980,Automatic,1000,Diesel,145,62.8,1.5
33,A Class,2020,28128,Automatic,2563,Petrol,145,47.9,1.3
38,C Class,2020,31790,Automatic,3500,Petrol,145,64.2,2.0
57,GLE Class,2020,48995,Automatic,3000,Diesel,145,36.7,2.0
...,...,...,...,...,...,...,...,...,...
13053,A Class,2020,27995,Automatic,2500,Diesel,145,67.3,1.5
13056,GLE Class,2020,58450,Automatic,1159,Diesel,150,32.8,2.9
13113,C Class,2020,30999,Automatic,1000,Diesel,145,64.2,2.0
13114,C Class,2020,35999,Automatic,500,Diesel,145,55.4,2.0
13115,B Class,2020,24699,Automatic,2500,Diesel,145,55.4,2.0